### ISSUE TITLE
Error in domain extraction

### ISSUE THREAD

**Issue by ghost** [Synchro/regdom-php#2]
In doing some further testing I noticed another problem with this code... it appears to work fine to extract normal domains with extensions that only contain one period "."

However, take for example any .co.uk domain and it doesn't work properly...  

``` php
$domain = 'sub.domain.gov.uk';
require_once('effectiveTLDs.inc.php');
$tldTree = require_once('regDomain.inc.php');
$domain = getRegisteredDomain($domain, $tldTree);
var_dump($domain);
```

This returns "gov.uk" instead of the expected "domain.gov.uk". Am I missing something or is this a bug?

**Comment by Synchro** [comment]
I think you're missing something! Regdom is intended to extract the "effective TLD", and the reason for wanting that is that there are only a limited number of them, so it's a useful thing to know in validation. An effective TLD is not an actual TLD, but it acts like one and has associated registration rules/governing body etc.

Given two domains like:

thing1.thing2.example.com
thing1.thing2.example.uk

you would have no way of knowing whether either of those is valid. Regdom can tell you that '.com' is just fine, but that 'example.uk' is invalid because it's not an allowed effective TLD, _without_ having to do a DNS lookup or whois. In your example, `.gov.uk` is the effective TLD. The `domain` bit can be anything, so it's not something you can validate on beyond simple DNS naming rules and is thus not included in the regdom database.

**Comment by mindsharelabs** [comment]
Thanks for the reply... sorry if I'm being thick, but why does this code return the full domain + extension and the above code only returns the extension?

``` php
$domain = 'sub.domain.com';
require_once('effectiveTLDs.inc.php');
$tldTree = require_once('regDomain.inc.php');
$domain = getRegisteredDomain($domain, $tldTree);
var_dump($domain);
```

This returns "domain.com" ... the former example only returns "gov.uk"

**Comment by Synchro** [comment]
There is something odd going on there. I've altered the generator to make the resulting arrays easier to read with some indentation. The UK section contains:

```
  'uk' => array(
    '*' => array(),
    'nhs' => array(
      '*' => array()),
    'police' => array(
      '*' => array()),
    'sch' => array(
      '*' => array()),
    'bl' => array(
'!' => ''),
    'british-library' => array(
'!' => ''),
    'jet' => array(
'!' => ''),
    'mod' => array(
'!' => ''),
    'national-library-scotland' => array(
'!' => ''),
    'nel' => array(
'!' => ''),
    'nic' => array(
'!' => ''),
    'nls' => array(
'!' => ''),
    'parliament' => array(
'!' => '')),
```

Which I'm surprised to see doesn't contain entries for gov or co! I've not really looked into the database much before, but I guess it is what it is!

**Comment by mindsharelabs** [comment]
Thanks that definitely seems to explain the issue... I wonder why those are not in the list? Please let me know if you figure anything else out. Cheers.
